name: Publish to GitHub Pages

on:
  push:
    branches: [ gmc ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: build
